# Generated by Django 4.0.6 on 2023-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=256, null=True)),
                ('sender_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('status', models.CharField(default='unread', max_length=32)),
            ],
        ),
    ]
