# Generated by Django 4.0.6 on 2023-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRecord',
            fields=[
                ('appointment_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('visitor_name', models.CharField(default='', max_length=32)),
                ('visitor_identity', models.CharField(default='', max_length=32)),
                ('visit_time', models.DateTimeField()),
                ('phone_number', models.CharField(default='', max_length=32)),
                ('code', models.CharField(default='', max_length=32)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
