# Generated by Django 4.0.6 on 2023-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('maintenance_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=255)),
                ('commit_time', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('room_name', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('maintain_time', models.DateTimeField()),
                ('maintain_user_id', models.IntegerField()),
                ('solution', models.CharField(max_length=255)),
                ('solve_time', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'db_table': 'maintenance_record',
            },
        ),
    ]
