# Generated by Django 4.0.6 on 2023-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintain_user_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='solve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(default='已报修', max_length=32),
        ),
    ]
