"""
Django settings for Buiding project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import yaml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with open("./secrets.yaml", 'r') as f:
    SECRETS = yaml.safe_load(f)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yep8s)c$xn(v5q3a1n&z&io)mpeimdim)b-lb&g88&-)q5sxcj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'notifications',
    'django_crontab',
    'user',
    'space',
    'maintain',
    'message',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'Buiding.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Buiding.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 本地测试版本数据库
        'ENGINE': 'django.db.backends.mysql',
        'NAME': SECRETS['database']['name'],
        'USER': SECRETS['database']['user'],
        'HOST': SECRETS['database']['host'],
        'PASSWORD': SECRETS['database']['password'],
        # 'PORT': SECRETS['database']['port_1'],
        'PORT': SECRETS['database']['port_2'],
        # 'PORT': SECRETS['database']['port_3'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_ALLOW_ALL = True

CRONJOBS = [
    # 初级模式
    ('0 1 * * *', 'utils.task.update_rent_message'),
    ('30 * * * *', 'utils.task.send_message'),
    ('*/5 * * * *', 'utils.task.send_email'),
]

# 发送邮件的配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 发送邮件的地址
EMAIL_HOST = 'smtp.163.com'  # 固定的
# 端口号
EMAIL_PORT = 25  # 不用改变
# 发送邮件的邮箱（填写刚刚注册授权码的邮箱）
EMAIL_HOST_USER = 'moshu1632022@163.com'
# 在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'TVBXGPUIKMCTUWSX'

# 由于使用25端口，一般都不使用TLS机密，SSL和TSL只需要设置一个，他们同时为True或False
# EMAIL_USE_LS = True   # 这里必须是 True，否则发送不成功
# 收件人看到的发件人
EMAIL_FROM = 'Smile大厦<moshu1632022@163.com>'  # 里面的邮箱地址必须和上面发送邮件的邮箱相同，否则无法成功发送！

# 发送短信配置
APP_ID = SECRETS['sms']['appid']
