# Generated by Django 4.0.6 on 2023-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('payment_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('pay_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment_record',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sign_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '租赁',
                'verbose_name_plural': '租赁',
                'db_table': 'rent',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('room_name', models.CharField(max_length=255)),
                ('is_empty', models.BooleanField()),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
            },
        ),
    ]
