# Generated by Django 4.0.6 on 2023-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
                ('email', models.CharField(default='', max_length=32)),
                ('identity', models.CharField(default='', max_length=16)),
                ('is_delete', models.BooleanField(default=False)),
                ('legal_entity_name', models.CharField(blank=True, default='', max_length=32)),
                ('company_name', models.CharField(blank=True, default='', max_length=32)),
                ('contact_person', models.CharField(default='', max_length=32)),
                ('contact_phone', models.CharField(default='', max_length=32)),
                ('is_working', models.BooleanField(default=False)),
                ('job_category', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
    ]
