# Generated by Django 4.0.6 on 2023-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_entity_name',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
