# Generated by Django 4.0.6 on 2023-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_company_name_alter_user_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_entity_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
